### PR TITLE
Apocalypse Patch update

### PR DESCRIPTION
**Pull request by AshKapow**
After the big Apocalypse patch in Phasmo, there are a number of changes that have been made. I have tried my best to capture them all here (there may be more that I'm missing).

This should resolve:
#62 
#63 
#64 
(and a couple of other smaller fixes that I've found)

There are no fundamental changes, just additions/removals of items/maps/objectives within the game.

### CODE REVIEW

**Comment by AshKapow** [comment]
I can see that my auto-formatting has auto-formatted some of the files. Let me know if that's an issue and I can revert them

**Comment by AshKapow** [comment]
Closing as this is now covered in #69

**Comment by GlitchedMythos** [comment]
@AshKapow Thank you for submitting the PR. My sincerest apologies that I was taking a break while you submitted.

**Comment by GlitchedMythos** [comment]
Closed as #69 covers everything

**Comment by AshKapow** [comment]
@GlitchedMythos no worries! Life always comes first.

**Pull request closed without merging**
