### PR TITLE
Cursed Possessions Update

### PR DESCRIPTION
**Pull request by billyjbryant**
## Description

PR to bring widget in line with the Cursed Possessions Update including adding the new Possessions and refactoring Sightings.

### Changes: 
* Re-worked Sightings to use the `!sight` command instead of having individual commands for each sighting
* Added `!poss` command to toggle possessions on or off
* Added base code for switching Evidence selection to a single command in future updates
* Added the ability to hide inactive sightings
* Refactored JSON based on commits from @TheSquall in #45

### CODE REVIEW

**Comment by billyjbryant** [comment]
@TheSquall can you review again please.

**Comment by billyjbryant** [comment]
@GlitchedMythos have any questions?

**Comment by GlitchedMythos** [comment]
> @GlitchedMythos have any questions?

I believe we need to remove set dirty water since it has been moved to !sighting

**Comment by billyjbryant** [comment]
I thought I had, I'll double check

**Comment by billyjbryant** [comment]
Done

**Pull request merged**
