### PR TITLE
Tempest Update (8.1)

### LINKED ISSUE #75: Mods not able to update widget after Apocalypse patch (part two)
Continuation from #72

I've been through with one of the streamers now with debugging enabled. They attempted with Mods, VIP and Trusted Users allowed. Still, for whoever tried to use the widget (not including the streamer), the user level came up as 'undefined' -- is it possible to be an issue with the widget picking up the user badges in some cases?

### PR DESCRIPTION
**Pull request by billyjbryant**
# Tempest Update (8.1)

## New Difficulties
* Insanity
* Challenge mode

## New Cursed Possession
* Monkey Paw

## Other changes
Fixes #75

### CODE REVIEW

**Comment by billyjbryant** [comment]
@ashkapow mind checking my work?

**Comment by AshKapow** [comment]
Checking now :)

**Review by AshKapow — APPROVED** [review]
New and existing functionality seems to be working OK in my channel

**Review by TrentonSarnowski — COMMENTED** [review]
Is there a specific reason for changing from double to single quotes?
It inflates the changes making it much harder to review.

**Comment by billyjbryant** [comment]
@TrentonSarnowski I honestly hadn't noticed the change, it was my IDE's auto-formatter. I can revert those changes; however, the only true change was to add the new SVG for the Monkey Paw in `widget.html`, Added the new difficulties and the code to support the monkey paw.

**Comment by billyjbryant** [comment]
I reverted all of the auto-formatting, @AshKapow mind re-validating your review?

**Review by AshKapow — APPROVED** [review]

**Comment by AshKapow** [comment]
Retested - all looking OK

**Review by TrentonSarnowski — APPROVED** [review]
Looks good to me, thanks for the IDE reversions they can be a mess to sort through

**Comment by billyjbryant** [comment]
@AshKapow : I have updated this to include fixes for the permissions bug identified in #75 can you please test to see if it resolves this for you and others?

**Review by AshKapow — APPROVED** [review]

**Pull request merged**
