### PR TITLE
Fixing bug with setting Map

### LINKED ISSUE #71: Cannot select "Sunny Meadows" map - defaults to "Sunny Meadows (Restricted)"
After the changes in the latest Apocolypse patch - we are now unable to select the "Sunny Meadows" maps, all other maps seem to work. If you choose "sunny" or "sunnymeadows" etc, it will show "Sunny Meadows (Restricted)" and not "Sunny Meadows". I'm guessing this is due to the new map lookup feature https://github.com/GlitchedMythos/se-widgets/blob/main/phasmophobia_evidence_tracker/widget.js#L1431

### LINKED ISSUE #72: Mods not able to update widget after Apocalypse patch
Not sure how easy this will be to replicate but I work with two streamers that use the widget regularly. Since the update, we have two scenarios.

- Streamer A: some of his mods can interact with the widget, others send the exact same commands, and nothing happens
- Streamer B: none of his mods can interact with the widget, but he is able to

Both have it set up to allow Moderators to interact with the widget and have had no issue before the update. Not sure on what was changed to affect this and I don't know about any other streamers using this widget. Sorry for easily replicable info for this issue

### PR DESCRIPTION
**Pull request by billyjbryant**
Setting Sunny Meadows now will not default to `Sunny Meadows (Restricted)`. This fixes #71

Also added in a Debug option for debugging command execution when there is an issue.  This will help diagnose #72

Updates the function to migrate from older VIP System to new Permissions. This fixes #72

### CODE REVIEW

**Comment by billyjbryant** [comment]
I also improved the functionality of migrating from prior VIP configurations to the new permissions system so this PR may actually fix #72

**Comment by AshKapow** [comment]
@billyjbryant confirmed fix for #71 

Nice update for the debug for #72

**Comment by billyjbryant** [comment]
@AshKapow thank you for testing and confirming the fix! 

@GlitchedMythos feel free to merge at your convenience :)

**Comment by GlitchedMythos** [comment]
Merged and StreamElements updated. Thank you @AshKapow and @billyjbryant

**Pull request merged**
